# coding: utf-8

"""
    JumpCloud Directory API

    JumpCloud RESTful APIs for the headless operation of core functions

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import jcapiv1
from jcapiv1.rest import ApiException
from jcapiv1.apis.default_api import DefaultApi


class TestDefaultApi(unittest.TestCase):
    """ DefaultApi unit test stubs """

    def setUp(self):
        self.api = jcapiv1.apis.default_api.DefaultApi()

    def tearDown(self):
        pass

    def test_command_trigger_webhook_post(self):
        """
        Test case for command_trigger_webhook_post

        
        """
        pass

    def test_commandresults_get(self):
        """
        Test case for commandresults_get

        
        """
        pass

    def test_commandresults_id_delete(self):
        """
        Test case for commandresults_id_delete

        
        """
        pass

    def test_commandresults_id_get(self):
        """
        Test case for commandresults_id_get

        
        """
        pass

    def test_commands_get(self):
        """
        Test case for commands_get

        
        """
        pass

    def test_commands_id_delete(self):
        """
        Test case for commands_id_delete

        
        """
        pass

    def test_commands_id_get(self):
        """
        Test case for commands_id_get

        
        """
        pass

    def test_commands_id_put(self):
        """
        Test case for commands_id_put

        
        """
        pass

    def test_commands_post(self):
        """
        Test case for commands_post

        
        """
        pass

    def test_search_systemusers_post(self):
        """
        Test case for search_systemusers_post

        
        """
        pass

    def test_systems_system_id_systemusers_get(self):
        """
        Test case for systems_system_id_systemusers_get

        
        """
        pass

    def test_systems_system_id_systemusers_put(self):
        """
        Test case for systems_system_id_systemusers_put

        
        """
        pass

    def test_systemusers_get(self):
        """
        Test case for systemusers_get

        
        """
        pass

    def test_systemusers_id_delete(self):
        """
        Test case for systemusers_id_delete

        
        """
        pass

    def test_systemusers_id_get(self):
        """
        Test case for systemusers_id_get

        
        """
        pass

    def test_systemusers_id_put(self):
        """
        Test case for systemusers_id_put

        
        """
        pass

    def test_systemusers_post(self):
        """
        Test case for systemusers_post

        
        """
        pass

    def test_systemusers_system_user_id_systems_get(self):
        """
        Test case for systemusers_system_user_id_systems_get

        
        """
        pass

    def test_systemusers_system_user_id_systems_put(self):
        """
        Test case for systemusers_system_user_id_systems_put

        
        """
        pass


if __name__ == '__main__':
    unittest.main()
