# coding: utf-8

"""
    JumpCloud APIs

     JumpCloud's V2 API. This set of endpoints allows JumpCloud customers to manage objects, groupings and mappings and interact with the JumpCloud Graph.  # noqa: E501

    OpenAPI spec version: 2.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from jcapiv2.models.active_directory_input import ActiveDirectoryInput  # noqa: F401,E501


class ActiveDirectoryOutput(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'domain': 'str',
        'id': 'str'
    }

    attribute_map = {
        'domain': 'domain',
        'id': 'id'
    }

    def __init__(self, domain=None, id=None):  # noqa: E501
        """ActiveDirectoryOutput - a model defined in Swagger"""  # noqa: E501

        self._domain = None
        self._id = None
        self.discriminator = None

        if domain is not None:
            self.domain = domain
        self.id = id

    @property
    def domain(self):
        """Gets the domain of this ActiveDirectoryOutput.  # noqa: E501

        Domain name for this Active Directory instance.  # noqa: E501

        :return: The domain of this ActiveDirectoryOutput.  # noqa: E501
        :rtype: str
        """
        return self._domain

    @domain.setter
    def domain(self, domain):
        """Sets the domain of this ActiveDirectoryOutput.

        Domain name for this Active Directory instance.  # noqa: E501

        :param domain: The domain of this ActiveDirectoryOutput.  # noqa: E501
        :type: str
        """

        self._domain = domain

    @property
    def id(self):
        """Gets the id of this ActiveDirectoryOutput.  # noqa: E501

        ObjectID of this Active Directory instance.  # noqa: E501

        :return: The id of this ActiveDirectoryOutput.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this ActiveDirectoryOutput.

        ObjectID of this Active Directory instance.  # noqa: E501

        :param id: The id of this ActiveDirectoryOutput.  # noqa: E501
        :type: str
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ActiveDirectoryOutput, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ActiveDirectoryOutput):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
