# coding: utf-8

"""
    JumpCloud APIs

     JumpCloud's V2 API. This set of endpoints allows JumpCloud customers to manage objects, groupings and mappings and interact with the JumpCloud Graph.  # noqa: E501

    OpenAPI spec version: 2.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class BulkUserUpdate(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'attributes': 'list[object]'
    }

    attribute_map = {
        'id': 'id',
        'attributes': 'attributes'
    }

    def __init__(self, id=None, attributes=None):  # noqa: E501
        """BulkUserUpdate - a model defined in Swagger"""  # noqa: E501

        self._id = None
        self._attributes = None
        self.discriminator = None

        if id is not None:
            self.id = id
        if attributes is not None:
            self.attributes = attributes

    @property
    def id(self):
        """Gets the id of this BulkUserUpdate.  # noqa: E501

        Object ID of the systemuser being updated  # noqa: E501

        :return: The id of this BulkUserUpdate.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this BulkUserUpdate.

        Object ID of the systemuser being updated  # noqa: E501

        :param id: The id of this BulkUserUpdate.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def attributes(self):
        """Gets the attributes of this BulkUserUpdate.  # noqa: E501

        Map of additional attributes.  # noqa: E501

        :return: The attributes of this BulkUserUpdate.  # noqa: E501
        :rtype: list[object]
        """
        return self._attributes

    @attributes.setter
    def attributes(self, attributes):
        """Sets the attributes of this BulkUserUpdate.

        Map of additional attributes.  # noqa: E501

        :param attributes: The attributes of this BulkUserUpdate.  # noqa: E501
        :type: list[object]
        """

        self._attributes = attributes

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, BulkUserUpdate):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
