# coding: utf-8

"""
    JumpCloud APIs

     JumpCloud's V2 API. This set of endpoints allows JumpCloud customers to manage objects, groupings and mappings and interact with the JumpCloud Graph.  # noqa: E501

    OpenAPI spec version: 2.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from jcapiv2.models.ldap_server_input import LdapServerInput  # noqa: F401,E501


class LdapServerOutput(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'name': 'str',
        'user_lockout_action': 'str',
        'user_password_expiration_action': 'str',
        'id': 'str'
    }

    attribute_map = {
        'name': 'name',
        'user_lockout_action': 'userLockoutAction',
        'user_password_expiration_action': 'userPasswordExpirationAction',
        'id': 'id'
    }

    def __init__(self, name=None, user_lockout_action=None, user_password_expiration_action=None, id=None):  # noqa: E501
        """LdapServerOutput - a model defined in Swagger"""  # noqa: E501

        self._name = None
        self._user_lockout_action = None
        self._user_password_expiration_action = None
        self._id = None
        self.discriminator = None

        if name is not None:
            self.name = name
        if user_lockout_action is not None:
            self.user_lockout_action = user_lockout_action
        if user_password_expiration_action is not None:
            self.user_password_expiration_action = user_password_expiration_action
        self.id = id

    @property
    def name(self):
        """Gets the name of this LdapServerOutput.  # noqa: E501

        The name of this LDAP server  # noqa: E501

        :return: The name of this LdapServerOutput.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this LdapServerOutput.

        The name of this LDAP server  # noqa: E501

        :param name: The name of this LdapServerOutput.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def user_lockout_action(self):
        """Gets the user_lockout_action of this LdapServerOutput.  # noqa: E501

        action to take; one of 'remove' or 'disable'  # noqa: E501

        :return: The user_lockout_action of this LdapServerOutput.  # noqa: E501
        :rtype: str
        """
        return self._user_lockout_action

    @user_lockout_action.setter
    def user_lockout_action(self, user_lockout_action):
        """Sets the user_lockout_action of this LdapServerOutput.

        action to take; one of 'remove' or 'disable'  # noqa: E501

        :param user_lockout_action: The user_lockout_action of this LdapServerOutput.  # noqa: E501
        :type: str
        """
        allowed_values = ["disable", "remove"]  # noqa: E501
        if user_lockout_action not in allowed_values:
            raise ValueError(
                "Invalid value for `user_lockout_action` ({0}), must be one of {1}"  # noqa: E501
                .format(user_lockout_action, allowed_values)
            )

        self._user_lockout_action = user_lockout_action

    @property
    def user_password_expiration_action(self):
        """Gets the user_password_expiration_action of this LdapServerOutput.  # noqa: E501

        action to take; one of 'remove' or 'disable'  # noqa: E501

        :return: The user_password_expiration_action of this LdapServerOutput.  # noqa: E501
        :rtype: str
        """
        return self._user_password_expiration_action

    @user_password_expiration_action.setter
    def user_password_expiration_action(self, user_password_expiration_action):
        """Sets the user_password_expiration_action of this LdapServerOutput.

        action to take; one of 'remove' or 'disable'  # noqa: E501

        :param user_password_expiration_action: The user_password_expiration_action of this LdapServerOutput.  # noqa: E501
        :type: str
        """
        allowed_values = ["disable", "remove"]  # noqa: E501
        if user_password_expiration_action not in allowed_values:
            raise ValueError(
                "Invalid value for `user_password_expiration_action` ({0}), must be one of {1}"  # noqa: E501
                .format(user_password_expiration_action, allowed_values)
            )

        self._user_password_expiration_action = user_password_expiration_action

    @property
    def id(self):
        """Gets the id of this LdapServerOutput.  # noqa: E501

        Unique identifier of this LDAP server  # noqa: E501

        :return: The id of this LdapServerOutput.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this LdapServerOutput.

        Unique identifier of this LDAP server  # noqa: E501

        :param id: The id of this LdapServerOutput.  # noqa: E501
        :type: str
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(LdapServerOutput, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, LdapServerOutput):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
