# coding: utf-8

"""
    JumpCloud APIs

     JumpCloud's V2 API. This set of endpoints allows JumpCloud customers to manage objects, groupings and mappings and interact with the JumpCloud Graph.  # noqa: E501

    OpenAPI spec version: 2.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from jcapiv2.models.office365_builtin_translation import Office365BuiltinTranslation  # noqa: F401,E501


class Office365TranslationRuleRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'built_in': 'Office365BuiltinTranslation'
    }

    attribute_map = {
        'built_in': 'builtIn'
    }

    def __init__(self, built_in=None):  # noqa: E501
        """Office365TranslationRuleRequest - a model defined in Swagger"""  # noqa: E501

        self._built_in = None
        self.discriminator = None

        if built_in is not None:
            self.built_in = built_in

    @property
    def built_in(self):
        """Gets the built_in of this Office365TranslationRuleRequest.  # noqa: E501


        :return: The built_in of this Office365TranslationRuleRequest.  # noqa: E501
        :rtype: Office365BuiltinTranslation
        """
        return self._built_in

    @built_in.setter
    def built_in(self, built_in):
        """Sets the built_in of this Office365TranslationRuleRequest.


        :param built_in: The built_in of this Office365TranslationRuleRequest.  # noqa: E501
        :type: Office365BuiltinTranslation
        """

        self._built_in = built_in

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Office365TranslationRuleRequest):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
