# coding: utf-8

"""
    JumpCloud APIs

     JumpCloud's V2 API. This set of endpoints allows JumpCloud customers to manage objects, groupings and mappings and interact with the JumpCloud Graph.  # noqa: E501

    OpenAPI spec version: 2.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class SystemInsightsSipConfig(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'collection_time': 'str',
        'config_flag': 'str',
        'enabled': 'int',
        'enabled_nvram': 'int',
        'system_id': 'str'
    }

    attribute_map = {
        'collection_time': 'collection_time',
        'config_flag': 'config_flag',
        'enabled': 'enabled',
        'enabled_nvram': 'enabled_nvram',
        'system_id': 'system_id'
    }

    def __init__(self, collection_time=None, config_flag=None, enabled=None, enabled_nvram=None, system_id=None):  # noqa: E501
        """SystemInsightsSipConfig - a model defined in Swagger"""  # noqa: E501

        self._collection_time = None
        self._config_flag = None
        self._enabled = None
        self._enabled_nvram = None
        self._system_id = None
        self.discriminator = None

        if collection_time is not None:
            self.collection_time = collection_time
        if config_flag is not None:
            self.config_flag = config_flag
        if enabled is not None:
            self.enabled = enabled
        if enabled_nvram is not None:
            self.enabled_nvram = enabled_nvram
        if system_id is not None:
            self.system_id = system_id

    @property
    def collection_time(self):
        """Gets the collection_time of this SystemInsightsSipConfig.  # noqa: E501


        :return: The collection_time of this SystemInsightsSipConfig.  # noqa: E501
        :rtype: str
        """
        return self._collection_time

    @collection_time.setter
    def collection_time(self, collection_time):
        """Sets the collection_time of this SystemInsightsSipConfig.


        :param collection_time: The collection_time of this SystemInsightsSipConfig.  # noqa: E501
        :type: str
        """

        self._collection_time = collection_time

    @property
    def config_flag(self):
        """Gets the config_flag of this SystemInsightsSipConfig.  # noqa: E501


        :return: The config_flag of this SystemInsightsSipConfig.  # noqa: E501
        :rtype: str
        """
        return self._config_flag

    @config_flag.setter
    def config_flag(self, config_flag):
        """Sets the config_flag of this SystemInsightsSipConfig.


        :param config_flag: The config_flag of this SystemInsightsSipConfig.  # noqa: E501
        :type: str
        """

        self._config_flag = config_flag

    @property
    def enabled(self):
        """Gets the enabled of this SystemInsightsSipConfig.  # noqa: E501


        :return: The enabled of this SystemInsightsSipConfig.  # noqa: E501
        :rtype: int
        """
        return self._enabled

    @enabled.setter
    def enabled(self, enabled):
        """Sets the enabled of this SystemInsightsSipConfig.


        :param enabled: The enabled of this SystemInsightsSipConfig.  # noqa: E501
        :type: int
        """

        self._enabled = enabled

    @property
    def enabled_nvram(self):
        """Gets the enabled_nvram of this SystemInsightsSipConfig.  # noqa: E501


        :return: The enabled_nvram of this SystemInsightsSipConfig.  # noqa: E501
        :rtype: int
        """
        return self._enabled_nvram

    @enabled_nvram.setter
    def enabled_nvram(self, enabled_nvram):
        """Sets the enabled_nvram of this SystemInsightsSipConfig.


        :param enabled_nvram: The enabled_nvram of this SystemInsightsSipConfig.  # noqa: E501
        :type: int
        """

        self._enabled_nvram = enabled_nvram

    @property
    def system_id(self):
        """Gets the system_id of this SystemInsightsSipConfig.  # noqa: E501


        :return: The system_id of this SystemInsightsSipConfig.  # noqa: E501
        :rtype: str
        """
        return self._system_id

    @system_id.setter
    def system_id(self, system_id):
        """Sets the system_id of this SystemInsightsSipConfig.


        :param system_id: The system_id of this SystemInsightsSipConfig.  # noqa: E501
        :type: str
        """

        self._system_id = system_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(SystemInsightsSipConfig, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SystemInsightsSipConfig):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
