# coding: utf-8

"""
    JumpCloud Directory API

    Allow cusotmers to manage the JumpCloud Directory objects, groupings and mappings.

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class PolicyTemplateValid(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, mac=None, windows=None):
        """
        PolicyTemplateValid - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'mac': 'object',
            'windows': 'object'
        }

        self.attribute_map = {
            'mac': 'mac',
            'windows': 'windows'
        }

        self._mac = mac
        self._windows = windows

    @property
    def mac(self):
        """
        Gets the mac of this PolicyTemplateValid.
        Key value pair (version being the key, true/false being the value).

        :return: The mac of this PolicyTemplateValid.
        :rtype: object
        """
        return self._mac

    @mac.setter
    def mac(self, mac):
        """
        Sets the mac of this PolicyTemplateValid.
        Key value pair (version being the key, true/false being the value).

        :param mac: The mac of this PolicyTemplateValid.
        :type: object
        """

        self._mac = mac

    @property
    def windows(self):
        """
        Gets the windows of this PolicyTemplateValid.
        Key value pair (version being the key, true/false being the value).

        :return: The windows of this PolicyTemplateValid.
        :rtype: object
        """
        return self._windows

    @windows.setter
    def windows(self, windows):
        """
        Sets the windows of this PolicyTemplateValid.
        Key value pair (version being the key, true/false being the value).

        :param windows: The windows of this PolicyTemplateValid.
        :type: object
        """

        self._windows = windows

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, PolicyTemplateValid):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
