# coding: utf-8

"""
    JumpCloud Directory API

    Allow cusotmers to manage the JumpCloud Directory objects, groupings and mappings.

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import jcapiv2
from jcapiv2.rest import ApiException
from jcapiv2.models.policy_template_valid import PolicyTemplateValid


class TestPolicyTemplateValid(unittest.TestCase):
    """ PolicyTemplateValid unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPolicyTemplateValid(self):
        """
        Test PolicyTemplateValid
        """
        model = jcapiv2.models.policy_template_valid.PolicyTemplateValid()


if __name__ == '__main__':
    unittest.main()
