# coding: utf-8

"""
    JumpCloud APIs

     JumpCloud's V1 API. This set of endpoints allows JumpCloud customers to manage commands, systems, & system users.

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import jcapiv1
from jcapiv1.rest import ApiException
from jcapiv1.models.application_config_idp_entity_id_tooltip import ApplicationConfigIdpEntityIdTooltip


class TestApplicationConfigIdpEntityIdTooltip(unittest.TestCase):
    """ ApplicationConfigIdpEntityIdTooltip unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testApplicationConfigIdpEntityIdTooltip(self):
        """
        Test ApplicationConfigIdpEntityIdTooltip
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = jcapiv1.models.application_config_idp_entity_id_tooltip.ApplicationConfigIdpEntityIdTooltip()
        pass


if __name__ == '__main__':
    unittest.main()
