# coding: utf-8

"""
    JumpCloud APIs

     JumpCloud's V1 API. This set of endpoints allows JumpCloud customers to manage commands, systems, & system users.  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import jcapiv1
from jcapiv1.models.system_system_insights import SystemSystemInsights  # noqa: E501
from jcapiv1.rest import ApiException


class TestSystemSystemInsights(unittest.TestCase):
    """SystemSystemInsights unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSystemSystemInsights(self):
        """Test SystemSystemInsights"""
        # FIXME: construct object with mandatory attributes with example values
        # model = jcapiv1.models.system_system_insights.SystemSystemInsights()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
