# coding: utf-8

"""
    JumpCloud APIs

     JumpCloud's V2 API. This set of endpoints allows JumpCloud customers to manage objects, groupings and mappings and interact with the JumpCloud Graph.  # noqa: E501

    OpenAPI spec version: 2.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import jcapiv2
from jcapiv2.models.graph_management_req import GraphManagementReq  # noqa: E501
from jcapiv2.rest import ApiException


class TestGraphManagementReq(unittest.TestCase):
    """GraphManagementReq unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGraphManagementReq(self):
        """Test GraphManagementReq"""
        # FIXME: construct object with mandatory attributes with example values
        # model = jcapiv2.models.graph_management_req.GraphManagementReq()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
