# coding: utf-8

"""
    JumpCloud APIs

     JumpCloud's V2 API. This set of endpoints allows JumpCloud customers to manage objects, groupings and mappings and interact with the JumpCloud Graph.  # noqa: E501

    OpenAPI spec version: 2.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import jcapiv2
from jcapiv2.api.system_insights_api import SystemInsightsApi  # noqa: E501
from jcapiv2.rest import ApiException


class TestSystemInsightsApi(unittest.TestCase):
    """SystemInsightsApi unit test stubs"""

    def setUp(self):
        self.api = jcapiv2.api.system_insights_api.SystemInsightsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_systeminsights_list_apps(self):
        """Test case for systeminsights_list_apps

        List System Insights Apps  # noqa: E501
        """
        pass

    def test_systeminsights_list_apps_0(self):
        """Test case for systeminsights_list_apps_0

        List System Insights System Apps  # noqa: E501
        """
        pass

    def test_systeminsights_list_bitlocker_info(self):
        """Test case for systeminsights_list_bitlocker_info

        List System Insights Bitlocker Info  # noqa: E501
        """
        pass

    def test_systeminsights_list_bitlocker_info_0(self):
        """Test case for systeminsights_list_bitlocker_info_0

        List System Insights System Bitlocker Info  # noqa: E501
        """
        pass

    def test_systeminsights_list_browser_plugins(self):
        """Test case for systeminsights_list_browser_plugins

        List System Insights Browser Plugins  # noqa: E501
        """
        pass

    def test_systeminsights_list_browser_plugins_0(self):
        """Test case for systeminsights_list_browser_plugins_0

        List System Insights System Browser Plugins  # noqa: E501
        """
        pass

    def test_systeminsights_list_chrome_extensions(self):
        """Test case for systeminsights_list_chrome_extensions

        List System Insights Chrome Extensions  # noqa: E501
        """
        pass

    def test_systeminsights_list_chrome_extensions_0(self):
        """Test case for systeminsights_list_chrome_extensions_0

        List System Insights System Chrome Extensions  # noqa: E501
        """
        pass

    def test_systeminsights_list_disk_encryption(self):
        """Test case for systeminsights_list_disk_encryption

        List System Insights Disk Encryption  # noqa: E501
        """
        pass

    def test_systeminsights_list_disk_encryption_0(self):
        """Test case for systeminsights_list_disk_encryption_0

        List System Insights System Disk Encryption  # noqa: E501
        """
        pass

    def test_systeminsights_list_disk_info(self):
        """Test case for systeminsights_list_disk_info

        List System Insights Disk Info  # noqa: E501
        """
        pass

    def test_systeminsights_list_disk_info_0(self):
        """Test case for systeminsights_list_disk_info_0

        List System Insights System Disk Info  # noqa: E501
        """
        pass

    def test_systeminsights_list_etc_hosts(self):
        """Test case for systeminsights_list_etc_hosts

        List System Insights Etc Hosts  # noqa: E501
        """
        pass

    def test_systeminsights_list_etc_hosts_0(self):
        """Test case for systeminsights_list_etc_hosts_0

        List System Insights System Etc Hosts  # noqa: E501
        """
        pass

    def test_systeminsights_list_firefox_addons(self):
        """Test case for systeminsights_list_firefox_addons

        List System Insights Firefox Addons  # noqa: E501
        """
        pass

    def test_systeminsights_list_firefox_addons_0(self):
        """Test case for systeminsights_list_firefox_addons_0

        List System Insights System Firefox Addons  # noqa: E501
        """
        pass

    def test_systeminsights_list_groups(self):
        """Test case for systeminsights_list_groups

        List System Insights Groups  # noqa: E501
        """
        pass

    def test_systeminsights_list_groups_0(self):
        """Test case for systeminsights_list_groups_0

        List System Insights System Groups  # noqa: E501
        """
        pass

    def test_systeminsights_list_interface_addresses(self):
        """Test case for systeminsights_list_interface_addresses

        List System Insights Interface Addresses  # noqa: E501
        """
        pass

    def test_systeminsights_list_interface_addresses_0(self):
        """Test case for systeminsights_list_interface_addresses_0

        List System Insights System Interface Addresses  # noqa: E501
        """
        pass

    def test_systeminsights_list_kernel_info(self):
        """Test case for systeminsights_list_kernel_info

        List System Insights Kernel Info  # noqa: E501
        """
        pass

    def test_systeminsights_list_kernel_info_0(self):
        """Test case for systeminsights_list_kernel_info_0

        List System Insights System Kernel Info  # noqa: E501
        """
        pass

    def test_systeminsights_list_logical_drives(self):
        """Test case for systeminsights_list_logical_drives

        List System Insights Logical Drives  # noqa: E501
        """
        pass

    def test_systeminsights_list_logical_drives_0(self):
        """Test case for systeminsights_list_logical_drives_0

        List System Insights System Logical Drives  # noqa: E501
        """
        pass

    def test_systeminsights_list_mounts(self):
        """Test case for systeminsights_list_mounts

        List System Insights Mounts  # noqa: E501
        """
        pass

    def test_systeminsights_list_mounts_0(self):
        """Test case for systeminsights_list_mounts_0

        List System Insights System Mounts  # noqa: E501
        """
        pass

    def test_systeminsights_list_os_version(self):
        """Test case for systeminsights_list_os_version

        List System Insights OS Version  # noqa: E501
        """
        pass

    def test_systeminsights_list_os_version_0(self):
        """Test case for systeminsights_list_os_version_0

        List System Insights System OS Version  # noqa: E501
        """
        pass

    def test_systeminsights_list_patches(self):
        """Test case for systeminsights_list_patches

        List System Insights Patches  # noqa: E501
        """
        pass

    def test_systeminsights_list_patches_0(self):
        """Test case for systeminsights_list_patches_0

        List System Insights System Patches  # noqa: E501
        """
        pass

    def test_systeminsights_list_programs(self):
        """Test case for systeminsights_list_programs

        List System Insights Programs  # noqa: E501
        """
        pass

    def test_systeminsights_list_programs_0(self):
        """Test case for systeminsights_list_programs_0

        List System Insights System Programs  # noqa: E501
        """
        pass

    def test_systeminsights_list_safari_extensions(self):
        """Test case for systeminsights_list_safari_extensions

        List System Insights Safari Extensions  # noqa: E501
        """
        pass

    def test_systeminsights_list_safari_extensions_0(self):
        """Test case for systeminsights_list_safari_extensions_0

        List System Insights System Safari Extensions  # noqa: E501
        """
        pass

    def test_systeminsights_list_system_controls(self):
        """Test case for systeminsights_list_system_controls

        List System Insights System Control  # noqa: E501
        """
        pass

    def test_systeminsights_list_system_controls_0(self):
        """Test case for systeminsights_list_system_controls_0

        List System Insights System System Controls  # noqa: E501
        """
        pass

    def test_systeminsights_list_system_info(self):
        """Test case for systeminsights_list_system_info

        List System Insights System Info  # noqa: E501
        """
        pass

    def test_systeminsights_list_system_info_0(self):
        """Test case for systeminsights_list_system_info_0

        List System Insights System System Info  # noqa: E501
        """
        pass

    def test_systeminsights_list_uptime(self):
        """Test case for systeminsights_list_uptime

        List System Insights Uptime  # noqa: E501
        """
        pass

    def test_systeminsights_list_uptime_0(self):
        """Test case for systeminsights_list_uptime_0

        List System Insights System Uptime  # noqa: E501
        """
        pass

    def test_systeminsights_list_users(self):
        """Test case for systeminsights_list_users

        List System Insights Users  # noqa: E501
        """
        pass

    def test_systeminsights_list_users_0(self):
        """Test case for systeminsights_list_users_0

        List System Insights System Users  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
