# coding: utf-8

"""
    JumpCloud APIs

    V1 & V2 versions of JumpCloud's API. The next version of JumpCloud's API. This set of endpoints allows JumpCloud customers to manage objects, groupings and mappings. The most recent version of JumpCloud's API. This set of endpoints allows JumpCloud customers to manage objects, groupings and mappings.

    OpenAPI spec version: 2.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import jcapiv2
from jcapiv2.rest import ApiException
from jcapiv2.models.inline_response_204 import InlineResponse204


class TestInlineResponse204(unittest.TestCase):
    """ InlineResponse204 unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse204(self):
        """
        Test InlineResponse204
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = jcapiv2.models.inline_response_204.InlineResponse204()
        pass


if __name__ == '__main__':
    unittest.main()
