# coding: utf-8

"""
    JumpCloud APIs

    V1 & V2 versions of JumpCloud's API. The next version of JumpCloud's API. This set of endpoints allows JumpCloud customers to manage objects, groupings and mappings. The most recent version of JumpCloud's API. This set of endpoints allows JumpCloud customers to manage objects, groupings and mappings.

    OpenAPI spec version: 2.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import jcapiv2
from jcapiv2.rest import ApiException
from jcapiv2.apis.directories_api import DirectoriesApi


class TestDirectoriesApi(unittest.TestCase):
    """ DirectoriesApi unit test stubs """

    def setUp(self):
        self.api = jcapiv2.apis.directories_api.DirectoriesApi()

    def tearDown(self):
        pass

    def test_directories_list(self):
        """
        Test case for directories_list

        List All Directories
        """
        pass


if __name__ == '__main__':
    unittest.main()
