# coding: utf-8

"""
    JumpCloud APIs

     JumpCloud's V2 API. This set of endpoints allows JumpCloud customers to manage objects, groupings and mappings and interact with the JumpCloud Graph.  # noqa: E501

    OpenAPI spec version: 2.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import jcapiv2
from jcapiv2.models.office_365_translation_rule import Office365TranslationRule  # noqa: E501
from jcapiv2.rest import ApiException


class TestOffice365TranslationRule(unittest.TestCase):
    """Office365TranslationRule unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOffice365TranslationRule(self):
        """Test Office365TranslationRule"""
        # FIXME: construct object with mandatory attributes with example values
        # model = jcapiv2.models.office_365_translation_rule.Office365TranslationRule()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
