# coding: utf-8

"""
    JumpCloud APIs

     JumpCloud's V2 API. This set of endpoints allows JumpCloud customers to manage objects, groupings and mappings and interact with the JumpCloud Graph.

    OpenAPI spec version: 2.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import jcapiv2
from jcapiv2.rest import ApiException
from jcapiv2.models.user_group import UserGroup


class TestUserGroup(unittest.TestCase):
    """ UserGroup unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUserGroup(self):
        """
        Test UserGroup
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = jcapiv2.models.user_group.UserGroup()
        pass


if __name__ == '__main__':
    unittest.main()
