# coding: utf-8

"""
    JumpCloud APIs

     JumpCloud's V2 API. This set of endpoints allows JumpCloud customers to manage objects, groupings and mappings and interact with the JumpCloud Graph.  # noqa: E501

    OpenAPI spec version: 2.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import jcapiv2
from jcapiv2.models.salesforce_knowledge_list_output import SalesforceKnowledgeListOutput  # noqa: E501
from jcapiv2.rest import ApiException


class TestSalesforceKnowledgeListOutput(unittest.TestCase):
    """SalesforceKnowledgeListOutput unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSalesforceKnowledgeListOutput(self):
        """Test SalesforceKnowledgeListOutput"""
        # FIXME: construct object with mandatory attributes with example values
        # model = jcapiv2.models.salesforce_knowledge_list_output.SalesforceKnowledgeListOutput()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
