# coding: utf-8

"""
    JumpCloud APIs

     JumpCloud's V1 API. This set of endpoints allows JumpCloud customers to manage commands, systems, & system users.  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from jcapiv1.models.application_config_acs_url_tooltip import ApplicationConfigAcsUrlTooltip  # noqa: F401,E501


class ApplicationConfigAcsUrl(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'label': 'str',
        'position': 'int',
        'read_only': 'bool',
        'required': 'bool',
        'tooltip': 'ApplicationConfigAcsUrlTooltip',
        'type': 'str',
        'value': 'str',
        'visible': 'bool'
    }

    attribute_map = {
        'label': 'label',
        'position': 'position',
        'read_only': 'readOnly',
        'required': 'required',
        'tooltip': 'tooltip',
        'type': 'type',
        'value': 'value',
        'visible': 'visible'
    }

    def __init__(self, label=None, position=None, read_only=None, required=None, tooltip=None, type=None, value=None, visible=None):  # noqa: E501
        """ApplicationConfigAcsUrl - a model defined in Swagger"""  # noqa: E501

        self._label = None
        self._position = None
        self._read_only = None
        self._required = None
        self._tooltip = None
        self._type = None
        self._value = None
        self._visible = None
        self.discriminator = None

        if label is not None:
            self.label = label
        if position is not None:
            self.position = position
        if read_only is not None:
            self.read_only = read_only
        if required is not None:
            self.required = required
        if tooltip is not None:
            self.tooltip = tooltip
        if type is not None:
            self.type = type
        if value is not None:
            self.value = value
        if visible is not None:
            self.visible = visible

    @property
    def label(self):
        """Gets the label of this ApplicationConfigAcsUrl.  # noqa: E501


        :return: The label of this ApplicationConfigAcsUrl.  # noqa: E501
        :rtype: str
        """
        return self._label

    @label.setter
    def label(self, label):
        """Sets the label of this ApplicationConfigAcsUrl.


        :param label: The label of this ApplicationConfigAcsUrl.  # noqa: E501
        :type: str
        """

        self._label = label

    @property
    def position(self):
        """Gets the position of this ApplicationConfigAcsUrl.  # noqa: E501


        :return: The position of this ApplicationConfigAcsUrl.  # noqa: E501
        :rtype: int
        """
        return self._position

    @position.setter
    def position(self, position):
        """Sets the position of this ApplicationConfigAcsUrl.


        :param position: The position of this ApplicationConfigAcsUrl.  # noqa: E501
        :type: int
        """

        self._position = position

    @property
    def read_only(self):
        """Gets the read_only of this ApplicationConfigAcsUrl.  # noqa: E501


        :return: The read_only of this ApplicationConfigAcsUrl.  # noqa: E501
        :rtype: bool
        """
        return self._read_only

    @read_only.setter
    def read_only(self, read_only):
        """Sets the read_only of this ApplicationConfigAcsUrl.


        :param read_only: The read_only of this ApplicationConfigAcsUrl.  # noqa: E501
        :type: bool
        """

        self._read_only = read_only

    @property
    def required(self):
        """Gets the required of this ApplicationConfigAcsUrl.  # noqa: E501


        :return: The required of this ApplicationConfigAcsUrl.  # noqa: E501
        :rtype: bool
        """
        return self._required

    @required.setter
    def required(self, required):
        """Sets the required of this ApplicationConfigAcsUrl.


        :param required: The required of this ApplicationConfigAcsUrl.  # noqa: E501
        :type: bool
        """

        self._required = required

    @property
    def tooltip(self):
        """Gets the tooltip of this ApplicationConfigAcsUrl.  # noqa: E501


        :return: The tooltip of this ApplicationConfigAcsUrl.  # noqa: E501
        :rtype: ApplicationConfigAcsUrlTooltip
        """
        return self._tooltip

    @tooltip.setter
    def tooltip(self, tooltip):
        """Sets the tooltip of this ApplicationConfigAcsUrl.


        :param tooltip: The tooltip of this ApplicationConfigAcsUrl.  # noqa: E501
        :type: ApplicationConfigAcsUrlTooltip
        """

        self._tooltip = tooltip

    @property
    def type(self):
        """Gets the type of this ApplicationConfigAcsUrl.  # noqa: E501


        :return: The type of this ApplicationConfigAcsUrl.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this ApplicationConfigAcsUrl.


        :param type: The type of this ApplicationConfigAcsUrl.  # noqa: E501
        :type: str
        """

        self._type = type

    @property
    def value(self):
        """Gets the value of this ApplicationConfigAcsUrl.  # noqa: E501


        :return: The value of this ApplicationConfigAcsUrl.  # noqa: E501
        :rtype: str
        """
        return self._value

    @value.setter
    def value(self, value):
        """Sets the value of this ApplicationConfigAcsUrl.


        :param value: The value of this ApplicationConfigAcsUrl.  # noqa: E501
        :type: str
        """

        self._value = value

    @property
    def visible(self):
        """Gets the visible of this ApplicationConfigAcsUrl.  # noqa: E501


        :return: The visible of this ApplicationConfigAcsUrl.  # noqa: E501
        :rtype: bool
        """
        return self._visible

    @visible.setter
    def visible(self, visible):
        """Sets the visible of this ApplicationConfigAcsUrl.


        :param visible: The visible of this ApplicationConfigAcsUrl.  # noqa: E501
        :type: bool
        """

        self._visible = visible

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ApplicationConfigAcsUrl, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ApplicationConfigAcsUrl):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
