# coding: utf-8

"""
    JumpCloud APIs

     JumpCloud's V1 API. This set of endpoints allows JumpCloud customers to manage commands, systems, & system users.  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class ApplicationtemplateJit(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'attributes': 'object',
        'create_only': 'bool'
    }

    attribute_map = {
        'attributes': 'attributes',
        'create_only': 'createOnly'
    }

    def __init__(self, attributes=None, create_only=None):  # noqa: E501
        """ApplicationtemplateJit - a model defined in Swagger"""  # noqa: E501

        self._attributes = None
        self._create_only = None
        self.discriminator = None

        if attributes is not None:
            self.attributes = attributes
        if create_only is not None:
            self.create_only = create_only

    @property
    def attributes(self):
        """Gets the attributes of this ApplicationtemplateJit.  # noqa: E501


        :return: The attributes of this ApplicationtemplateJit.  # noqa: E501
        :rtype: object
        """
        return self._attributes

    @attributes.setter
    def attributes(self, attributes):
        """Sets the attributes of this ApplicationtemplateJit.


        :param attributes: The attributes of this ApplicationtemplateJit.  # noqa: E501
        :type: object
        """

        self._attributes = attributes

    @property
    def create_only(self):
        """Gets the create_only of this ApplicationtemplateJit.  # noqa: E501


        :return: The create_only of this ApplicationtemplateJit.  # noqa: E501
        :rtype: bool
        """
        return self._create_only

    @create_only.setter
    def create_only(self, create_only):
        """Sets the create_only of this ApplicationtemplateJit.


        :param create_only: The create_only of this ApplicationtemplateJit.  # noqa: E501
        :type: bool
        """

        self._create_only = create_only

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ApplicationtemplateJit, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ApplicationtemplateJit):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
