# coding: utf-8

"""
    JumpCloud APIs

    V1 & V2 versions of JumpCloud's API. The previous version of JumpCloud's API. This set of endpoints allows JumpCloud customers to manage commands, systems, & system users.

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class InlineResponse200ConfigIdpEntityIdTooltip(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'template': 'str',
        'variables': 'InlineResponse200ConfigIdpEntityIdTooltipVariables'
    }

    attribute_map = {
        'template': 'template',
        'variables': 'variables'
    }

    def __init__(self, template=None, variables=None):
        """
        InlineResponse200ConfigIdpEntityIdTooltip - a model defined in Swagger
        """

        self._template = None
        self._variables = None

        if template is not None:
          self.template = template
        if variables is not None:
          self.variables = variables

    @property
    def template(self):
        """
        Gets the template of this InlineResponse200ConfigIdpEntityIdTooltip.

        :return: The template of this InlineResponse200ConfigIdpEntityIdTooltip.
        :rtype: str
        """
        return self._template

    @template.setter
    def template(self, template):
        """
        Sets the template of this InlineResponse200ConfigIdpEntityIdTooltip.

        :param template: The template of this InlineResponse200ConfigIdpEntityIdTooltip.
        :type: str
        """

        self._template = template

    @property
    def variables(self):
        """
        Gets the variables of this InlineResponse200ConfigIdpEntityIdTooltip.

        :return: The variables of this InlineResponse200ConfigIdpEntityIdTooltip.
        :rtype: InlineResponse200ConfigIdpEntityIdTooltipVariables
        """
        return self._variables

    @variables.setter
    def variables(self, variables):
        """
        Sets the variables of this InlineResponse200ConfigIdpEntityIdTooltip.

        :param variables: The variables of this InlineResponse200ConfigIdpEntityIdTooltip.
        :type: InlineResponse200ConfigIdpEntityIdTooltipVariables
        """

        self._variables = variables

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, InlineResponse200ConfigIdpEntityIdTooltip):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
