# coding: utf-8

"""
    JumpCloud APIs

    V1 & V2 versions of JumpCloud's API. The previous version of JumpCloud's API. This set of endpoints allows JumpCloud customers to manage commands, systems, & system users.

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class Systemuserbindingsput(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'add': 'list[str]',
        'remove': 'list[str]'
    }

    attribute_map = {
        'add': 'add',
        'remove': 'remove'
    }

    def __init__(self, add=None, remove=None):
        """
        Systemuserbindingsput - a model defined in Swagger
        """

        self._add = None
        self._remove = None

        self.add = add
        self.remove = remove

    @property
    def add(self):
        """
        Gets the add of this Systemuserbindingsput.
        The list of systemuser ids to be added to this system.

        :return: The add of this Systemuserbindingsput.
        :rtype: list[str]
        """
        return self._add

    @add.setter
    def add(self, add):
        """
        Sets the add of this Systemuserbindingsput.
        The list of systemuser ids to be added to this system.

        :param add: The add of this Systemuserbindingsput.
        :type: list[str]
        """
        if add is None:
            raise ValueError("Invalid value for `add`, must not be `None`")

        self._add = add

    @property
    def remove(self):
        """
        Gets the remove of this Systemuserbindingsput.
        The list of systemuser ids to be removed from this system.

        :return: The remove of this Systemuserbindingsput.
        :rtype: list[str]
        """
        return self._remove

    @remove.setter
    def remove(self, remove):
        """
        Sets the remove of this Systemuserbindingsput.
        The list of systemuser ids to be removed from this system.

        :param remove: The remove of this Systemuserbindingsput.
        :type: list[str]
        """
        if remove is None:
            raise ValueError("Invalid value for `remove`, must not be `None`")

        self._remove = remove

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, Systemuserbindingsput):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
