# coding: utf-8

# flake8: noqa

"""
    JumpCloud API

    # Overview  JumpCloud's V2 API. This set of endpoints allows JumpCloud customers to manage objects, groupings and mappings and interact with the JumpCloud Graph.  # Directory Objects  This API offers the ability to interact with some of our core features; otherwise known as Directory Objects. The Directory Objects are:  * Commands * Policies * Policy Groups * Applications * Systems * Users * User Groups * System Groups * Radius Servers * Directories: Office 365, LDAP,G-Suite, Active Directory * Duo accounts and applications.  The Directory Object is an important concept to understand in order to successfully use JumpCloud API.  ## JumpCloud Graph  We've also introduced the concept of the JumpCloud Graph along with  Directory Objects. The Graph is a powerful aspect of our platform which will enable you to associate objects with each other, or establish membership for certain objects to become members of other objects.  Specific `GET` endpoints will allow you to traverse the JumpCloud Graph to return all indirect and directly bound objects in your organization.  | ![alt text](https://s3.amazonaws.com/jumpcloud-kb/Knowledge+Base+Photos/API+Docs/jumpcloud_graph.png \"JumpCloud Graph Model Example\") | |:--:| | **This diagram highlights our association and membership model as it relates to Directory Objects.** |  # API Key  ## Access Your API Key  To locate your API Key:  1. Log into the [JumpCloud Admin Console](https://console.jumpcloud.com/). 2. Go to the username drop down located in the top-right of the Console. 3. Retrieve your API key from API Settings.  ## API Key Considerations  This API key is associated to the currently logged in administrator. Other admins will have different API keys.  **WARNING** Please keep this API key secret, as it grants full access to any data accessible via your JumpCloud console account.  You can also reset your API key in the same location in the JumpCloud Admin Console.  ## Recycling or Resetting Your API Key  In order to revoke access with the current API key, simply reset your API key. This will render all calls using the previous API key inaccessible.  Your API key will be passed in as a header with the header name \"x-api-key\".  ```bash curl -H \"x-api-key: [YOUR_API_KEY_HERE]\" \"https://console.jumpcloud.com/api/v2/systemgroups\" ```  # System Context  * [Introduction](#introduction) * [Supported endpoints](#supported-endpoints) * [Response codes](#response-codes) * [Authentication](#authentication) * [Additional examples](#additional-examples) * [Third party](#third-party)  ## Introduction  JumpCloud System Context Authorization is an alternative way to authenticate with a subset of JumpCloud's REST APIs. Using this method, a system can manage its information and resource associations, allowing modern auto provisioning environments to scale as needed.  **Notes:**   * The following documentation applies to Linux Operating Systems only.  * Systems that have been automatically enrolled using Apple's Device Enrollment Program (DEP) or systems enrolled using the User Portal install are not eligible to use the System Context API to prevent unauthorized access to system groups and resources. If a script that utilizes the System Context API is invoked on a system enrolled in this way, it will display an error.  ## Supported Endpoints  JumpCloud System Context Authorization can be used in conjunction with Systems endpoints found in the V1 API and certain System Group endpoints found in the v2 API.  * A system may fetch, alter, and delete metadata about itself, including manipulating a system's Group and Systemuser associations,   * `/api/systems/{system_id}` | [`GET`](https://docs.jumpcloud.com/api/1.0/index.html#operation/systems_get) [`PUT`](https://docs.jumpcloud.com/api/1.0/index.html#operation/systems_put) * A system may delete itself from your JumpCloud organization   * `/api/systems/{system_id}` | [`DELETE`](https://docs.jumpcloud.com/api/1.0/index.html#operation/systems_delete) * A system may fetch its direct resource associations under v2 (Groups)   * `/api/v2/systems/{system_id}/memberof` | [`GET`](https://docs.jumpcloud.com/api/2.0/index.html#operation/graph_systemGroupMembership)   * `/api/v2/systems/{system_id}/associations` | [`GET`](https://docs.jumpcloud.com/api/2.0/index.html#operation/graph_systemAssociationsList)   * `/api/v2/systems/{system_id}/users` | [`GET`](https://docs.jumpcloud.com/api/2.0/index.html#operation/graph_systemTraverseUser) * A system may alter its direct resource associations under v2 (Groups)   * `/api/v2/systems/{system_id}/associations` | [`POST`](https://docs.jumpcloud.com/api/2.0/index.html#operation/graph_systemAssociationsPost) * A system may alter its System Group associations   * `/api/v2/systemgroups/{group_id}/members` | [`POST`](https://docs.jumpcloud.com/api/2.0/index.html#operation/graph_systemGroupMembersPost)     * _NOTE_ If a system attempts to alter the system group membership of a different system the request will be rejected  ## Response Codes  If endpoints other than those described above are called using the System Context API, the server will return a `401` response.  ## Authentication  To allow for secure access to our APIs, you must authenticate each API request. JumpCloud System Context Authorization uses [HTTP Signatures](https://tools.ietf.org/html/draft-cavage-http-signatures-00) to authenticate API requests. The HTTP Signatures sent with each request are similar to the signatures used by the Amazon Web Services REST API. To help with the request-signing process, we have provided an [example bash script](https://github.com/TheJumpCloud/SystemContextAPI/blob/master/examples/shell/SigningExample.sh). This example API request simply requests the entire system record. You must be root, or have permissions to access the contents of the `/opt/jc` directory to generate a signature.  Here is a breakdown of the example script with explanations.  First, the script extracts the systemKey from the JSON formatted `/opt/jc/jcagent.conf` file.  ```bash #!/bin/bash conf=\"`cat /opt/jc/jcagent.conf`\" regex=\"systemKey\\\":\\\"(\\w+)\\\"\"  if [[ $conf =~ $regex ]] ; then   systemKey=\"${BASH_REMATCH[1]}\" fi ```  Then, the script retrieves the current date in the correct format.  ```bash now=`date -u \"+%a, %d %h %Y %H:%M:%S GMT\"`; ```  Next, we build a signing string to demonstrate the expected signature format. The signed string must consist of the [request-line](https://tools.ietf.org/html/rfc2616#page-35) and the date header, separated by a newline character.  ```bash signstr=\"GET /api/systems/${systemKey} HTTP/1.1\\ndate: ${now}\" ```  The next step is to calculate and apply the signature. This is a two-step process:  1. Create a signature from the signing string using the JumpCloud Agent private key: ``printf \"$signstr\" | openssl dgst -sha256 -sign /opt/jc/client.key`` 2. Then Base64-encode the signature string and trim off the newline characters: ``| openssl enc -e -a | tr -d '\\n'``  The combined steps above result in:  ```bash signature=`printf \"$signstr\" | openssl dgst -sha256 -sign /opt/jc/client.key | openssl enc -e -a | tr -d '\\n'` ; ```  Finally, we make sure the API call sending the signature has the same Authorization and Date header values, HTTP method, and URL that were used in the signing string.  ```bash curl -iq \\   -H \"Accept: application/json\" \\   -H \"Content-Type: application/json\" \\   -H \"Date: ${now}\" \\   -H \"Authorization: Signature keyId=\\\"system/${systemKey}\\\",headers=\\\"request-line date\\\",algorithm=\\\"rsa-sha256\\\",signature=\\\"${signature}\\\"\" \\   --url https://console.jumpcloud.com/api/systems/${systemKey} ```  ### Input Data  All PUT and POST methods should use the HTTP Content-Type header with a value of 'application/json'. PUT methods are used for updating a record. POST methods are used to create a record.  The following example demonstrates how to update the `displayName` of the system.  ```bash signstr=\"PUT /api/systems/${systemKey} HTTP/1.1\\ndate: ${now}\" signature=`printf \"$signstr\" | openssl dgst -sha256 -sign /opt/jc/client.key | openssl enc -e -a | tr -d '\\n'` ;  curl -iq \\   -d \"{\\\"displayName\\\" : \\\"updated-system-name-1\\\"}\" \\   -X \"PUT\" \\   -H \"Content-Type: application/json\" \\   -H \"Accept: application/json\" \\   -H \"Date: ${now}\" \\   -H \"Authorization: Signature keyId=\\\"system/${systemKey}\\\",headers=\\\"request-line date\\\",algorithm=\\\"rsa-sha256\\\",signature=\\\"${signature}\\\"\" \\   --url https://console.jumpcloud.com/api/systems/${systemKey} ```  ### Output Data  All results will be formatted as JSON.  Here is an abbreviated example of response output:  ```json {   \"_id\": \"525ee96f52e144993e000015\",   \"agentServer\": \"lappy386\",   \"agentVersion\": \"0.9.42\",   \"arch\": \"x86_64\",   \"connectionKey\": \"127.0.0.1_51812\",   \"displayName\": \"ubuntu-1204\",   \"firstContact\": \"2013-10-16T19:30:55.611Z\",   \"hostname\": \"ubuntu-1204\"   ... ```  ## Additional Examples  ### Signing Authentication Example  This example demonstrates how to make an authenticated request to fetch the JumpCloud record for this system.  [SigningExample.sh](https://github.com/TheJumpCloud/SystemContextAPI/blob/master/examples/shell/SigningExample.sh)  ### Shutdown Hook  This example demonstrates how to make an authenticated request on system shutdown. Using an init.d script registered at run level 0, you can call the System Context API as the system is shutting down.  [Instance-shutdown-initd](https://github.com/TheJumpCloud/SystemContextAPI/blob/master/examples/instance-shutdown-initd) is an example of an init.d script that only runs at system shutdown.  After customizing the [instance-shutdown-initd](https://github.com/TheJumpCloud/SystemContextAPI/blob/master/examples/instance-shutdown-initd) script, you should install it on the system(s) running the JumpCloud agent.  1. Copy the modified [instance-shutdown-initd](https://github.com/TheJumpCloud/SystemContextAPI/blob/master/examples/instance-shutdown-initd) to `/etc/init.d/instance-shutdown`. 2. On Ubuntu systems, run `update-rc.d instance-shutdown defaults`. On RedHat/CentOS systems, run `chkconfig --add instance-shutdown`.  ## Third Party  ### Chef Cookbooks  [https://github.com/nshenry03/jumpcloud](https://github.com/nshenry03/jumpcloud)  [https://github.com/cjs226/jumpcloud](https://github.com/cjs226/jumpcloud)  # Multi-Tenant Portal Headers  Multi-Tenant Organization API Headers are available for JumpCloud Admins to use when making API requests from Organizations that have multiple managed organizations.  The `x-org-id` is a required header for all multi-tenant admins when making API requests to JumpCloud. This header will define to which organization you would like to make the request.  **NOTE** Single Tenant Admins do not need to provide this header when making an API request.  ## Header Value  `x-org-id`  ## API Response Codes  * `400` Malformed ID. * `400` x-org-id and Organization path ID do not match. * `401` ID not included for multi-tenant admin * `403` ID included on unsupported route. * `404` Organization ID Not Found.  ```bash curl -X GET https://console.jumpcloud.com/api/v2/directories \\   -H 'accept: application/json' \\   -H 'content-type: application/json' \\   -H 'x-api-key: {API_KEY}' \\   -H 'x-org-id: {ORG_ID}'  ```  ## To Obtain an Individual Organization ID via the UI  As a prerequisite, your Primary Organization will need to be setup for Multi-Tenancy. This provides access to the Multi-Tenant Organization Admin Portal.  1. Log into JumpCloud [Admin Console](https://console.jumpcloud.com). If you are a multi-tenant Admin, you will automatically be routed to the Multi-Tenant Admin Portal. 2. From the Multi-Tenant Portal's primary navigation bar, select the Organization you'd like to access. 3. You will automatically be routed to that Organization's Admin Console. 4. Go to Settings in the sub-tenant's primary navigation. 5. You can obtain your Organization ID below your Organization's Contact Information on the Settings page.  ## To Obtain All Organization IDs via the API  * You can make an API request to this endpoint using the API key of your Primary Organization.  `https://console.jumpcloud.com/api/organizations/` This will return all your managed organizations.  ```bash curl -X GET \\   https://console.jumpcloud.com/api/organizations/ \\   -H 'Accept: application/json' \\   -H 'Content-Type: application/json' \\   -H 'x-api-key: {API_KEY}' ```  # SDKs  You can find language specific SDKs that can help you kickstart your Integration with JumpCloud in the following GitHub repositories:  * [Python](https://github.com/TheJumpCloud/jcapi-python) * [Go](https://github.com/TheJumpCloud/jcapi-go) * [Ruby](https://github.com/TheJumpCloud/jcapi-ruby) * [Java](https://github.com/TheJumpCloud/jcapi-java)   # noqa: E501

    OpenAPI spec version: 2.0
    Contact: support@jumpcloud.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

# import apis into sdk package
from jcapiv2.api.active_directory_api import ActiveDirectoryApi
from jcapiv2.api.administrators_api import AdministratorsApi
from jcapiv2.api.apple_mdm_api import AppleMDMApi
from jcapiv2.api.applications_api import ApplicationsApi
from jcapiv2.api.authentication_policies_api import AuthenticationPoliciesApi
from jcapiv2.api.bulk_job_requests_api import BulkJobRequestsApi
from jcapiv2.api.command_results_api import CommandResultsApi
from jcapiv2.api.commands_api import CommandsApi
from jcapiv2.api.custom_emails_api import CustomEmailsApi
from jcapiv2.api.directories_api import DirectoriesApi
from jcapiv2.api.duo_api import DuoApi
from jcapiv2.api.g_suite_api import GSuiteApi
from jcapiv2.api.g_suite_import_api import GSuiteImportApi
from jcapiv2.api.graph_api import GraphApi
from jcapiv2.api.groups_api import GroupsApi
from jcapiv2.api.ip_lists_api import IPListsApi
from jcapiv2.api.image_api import ImageApi
from jcapiv2.api.ldap_servers_api import LDAPServersApi
from jcapiv2.api.logos_api import LogosApi
from jcapiv2.api.managed_service_provider_api import ManagedServiceProviderApi
from jcapiv2.api.office_365_api import Office365Api
from jcapiv2.api.office_365_import_api import Office365ImportApi
from jcapiv2.api.organizations_api import OrganizationsApi
from jcapiv2.api.policies_api import PoliciesApi
from jcapiv2.api.policy_group_associations_api import PolicyGroupAssociationsApi
from jcapiv2.api.policy_group_members__membership_api import PolicyGroupMembersMembershipApi
from jcapiv2.api.policy_groups_api import PolicyGroupsApi
from jcapiv2.api.policytemplates_api import PolicytemplatesApi
from jcapiv2.api.providers_api import ProvidersApi
from jcapiv2.api.radius_servers_api import RADIUSServersApi
from jcapiv2.api.scim_import_api import SCIMImportApi
from jcapiv2.api.samba_domains_api import SambaDomainsApi
from jcapiv2.api.software_apps_api import SoftwareAppsApi
from jcapiv2.api.subscriptions_api import SubscriptionsApi
from jcapiv2.api.system_group_associations_api import SystemGroupAssociationsApi
from jcapiv2.api.system_group_members__membership_api import SystemGroupMembersMembershipApi
from jcapiv2.api.system_groups_api import SystemGroupsApi
from jcapiv2.api.system_insights_api import SystemInsightsApi
from jcapiv2.api.systems_api import SystemsApi
from jcapiv2.api.user_group_associations_api import UserGroupAssociationsApi
from jcapiv2.api.user_group_members__membership_api import UserGroupMembersMembershipApi
from jcapiv2.api.user_groups_api import UserGroupsApi
from jcapiv2.api.users_api import UsersApi
from jcapiv2.api.workday_import_api import WorkdayImportApi
from jcapiv2.api.fde_api import FdeApi
# import ApiClient
from jcapiv2.api_client import ApiClient
from jcapiv2.configuration import Configuration
# import models into sdk package
from jcapiv2.models.ade import ADE
from jcapiv2.models.ades import ADES
from jcapiv2.models.active_directory_agent_get_output import ActiveDirectoryAgentGetOutput
from jcapiv2.models.active_directory_agent_input import ActiveDirectoryAgentInput
from jcapiv2.models.active_directory_agent_list_output import ActiveDirectoryAgentListOutput
from jcapiv2.models.active_directory_input import ActiveDirectoryInput
from jcapiv2.models.active_directory_output import ActiveDirectoryOutput
from jcapiv2.models.address import Address
from jcapiv2.models.administrator import Administrator
from jcapiv2.models.administrator_organization_link import AdministratorOrganizationLink
from jcapiv2.models.administrator_organization_link_req import AdministratorOrganizationLinkReq
from jcapiv2.models.all_of_autotask_ticketing_alert_configuration_list_records_items import AllOfAutotaskTicketingAlertConfigurationListRecordsItems
from jcapiv2.models.all_of_connect_wise_ticketing_alert_configuration_list_records_items import AllOfConnectWiseTicketingAlertConfigurationListRecordsItems
from jcapiv2.models.any_value import AnyValue
from jcapiv2.models.apple_mdm import AppleMDM
from jcapiv2.models.apple_mdm_device import AppleMdmDevice
from jcapiv2.models.apple_mdm_device_info import AppleMdmDeviceInfo
from jcapiv2.models.apple_mdm_device_security_info import AppleMdmDeviceSecurityInfo
from jcapiv2.models.apple_mdm_patch_input import AppleMdmPatchInput
from jcapiv2.models.apple_mdm_public_key_cert import AppleMdmPublicKeyCert
from jcapiv2.models.apple_mdm_signed_csr_plist import AppleMdmSignedCsrPlist
from jcapiv2.models.application_id_logo_body import ApplicationIdLogoBody
from jcapiv2.models.auth_info import AuthInfo
from jcapiv2.models.auth_input import AuthInput
from jcapiv2.models.auth_input_object import AuthInputObject
from jcapiv2.models.authinput_basic import AuthinputBasic
from jcapiv2.models.authinput_oauth import AuthinputOauth
from jcapiv2.models.authn_policy import AuthnPolicy
from jcapiv2.models.authn_policy_effect import AuthnPolicyEffect
from jcapiv2.models.authn_policy_input import AuthnPolicyInput
from jcapiv2.models.authn_policy_obligations import AuthnPolicyObligations
from jcapiv2.models.authn_policy_obligations_mfa import AuthnPolicyObligationsMfa
from jcapiv2.models.authn_policy_obligations_user_verification import AuthnPolicyObligationsUserVerification
from jcapiv2.models.authn_policy_resource_target import AuthnPolicyResourceTarget
from jcapiv2.models.authn_policy_targets import AuthnPolicyTargets
from jcapiv2.models.authn_policy_type import AuthnPolicyType
from jcapiv2.models.authn_policy_user_attribute_filter import AuthnPolicyUserAttributeFilter
from jcapiv2.models.authn_policy_user_attribute_target import AuthnPolicyUserAttributeTarget
from jcapiv2.models.authn_policy_user_group_target import AuthnPolicyUserGroupTarget
from jcapiv2.models.authn_policy_user_target import AuthnPolicyUserTarget
from jcapiv2.models.autotask_company import AutotaskCompany
from jcapiv2.models.autotask_company_resp import AutotaskCompanyResp
from jcapiv2.models.autotask_company_type_resp import AutotaskCompanyTypeResp
from jcapiv2.models.autotask_contract import AutotaskContract
from jcapiv2.models.autotask_contract_field import AutotaskContractField
from jcapiv2.models.autotask_contract_field_values import AutotaskContractFieldValues
from jcapiv2.models.autotask_integration import AutotaskIntegration
from jcapiv2.models.autotask_integration_patch_req import AutotaskIntegrationPatchReq
from jcapiv2.models.autotask_integration_req import AutotaskIntegrationReq
from jcapiv2.models.autotask_mapping_request import AutotaskMappingRequest
from jcapiv2.models.autotask_mapping_request_company import AutotaskMappingRequestCompany
from jcapiv2.models.autotask_mapping_request_contract import AutotaskMappingRequestContract
from jcapiv2.models.autotask_mapping_request_data import AutotaskMappingRequestData
from jcapiv2.models.autotask_mapping_request_organization import AutotaskMappingRequestOrganization
from jcapiv2.models.autotask_mapping_request_service import AutotaskMappingRequestService
from jcapiv2.models.autotask_mapping_response import AutotaskMappingResponse
from jcapiv2.models.autotask_mapping_response_company import AutotaskMappingResponseCompany
from jcapiv2.models.autotask_mapping_response_contract import AutotaskMappingResponseContract
from jcapiv2.models.autotask_mapping_response_organization import AutotaskMappingResponseOrganization
from jcapiv2.models.autotask_mapping_response_service import AutotaskMappingResponseService
from jcapiv2.models.autotask_service import AutotaskService
from jcapiv2.models.autotask_settings import AutotaskSettings
from jcapiv2.models.autotask_settings_patch_req import AutotaskSettingsPatchReq
from jcapiv2.models.autotask_ticketing_alert_configuration import AutotaskTicketingAlertConfiguration
from jcapiv2.models.autotask_ticketing_alert_configuration_list import AutotaskTicketingAlertConfigurationList
from jcapiv2.models.autotask_ticketing_alert_configuration_option import AutotaskTicketingAlertConfigurationOption
from jcapiv2.models.autotask_ticketing_alert_configuration_option_values import AutotaskTicketingAlertConfigurationOptionValues
from jcapiv2.models.autotask_ticketing_alert_configuration_options import AutotaskTicketingAlertConfigurationOptions
from jcapiv2.models.autotask_ticketing_alert_configuration_priority import AutotaskTicketingAlertConfigurationPriority
from jcapiv2.models.autotask_ticketing_alert_configuration_request import AutotaskTicketingAlertConfigurationRequest
from jcapiv2.models.autotask_ticketing_alert_configuration_resource import AutotaskTicketingAlertConfigurationResource
from jcapiv2.models.billing_integration_company_type import BillingIntegrationCompanyType
from jcapiv2.models.bulk_scheduled_statechange_create import BulkScheduledStatechangeCreate
from jcapiv2.models.bulk_user_create import BulkUserCreate
from jcapiv2.models.bulk_user_update import BulkUserUpdate
from jcapiv2.models.command_result_list import CommandResultList
from jcapiv2.models.command_result_list_results import CommandResultListResults
from jcapiv2.models.connect_wise_mapping_request import ConnectWiseMappingRequest
from jcapiv2.models.connect_wise_mapping_request_company import ConnectWiseMappingRequestCompany
from jcapiv2.models.connect_wise_mapping_request_data import ConnectWiseMappingRequestData
from jcapiv2.models.connect_wise_mapping_request_organization import ConnectWiseMappingRequestOrganization
from jcapiv2.models.connect_wise_mapping_response import ConnectWiseMappingResponse
from jcapiv2.models.connect_wise_mapping_response_addition import ConnectWiseMappingResponseAddition
from jcapiv2.models.connect_wise_settings import ConnectWiseSettings
from jcapiv2.models.connect_wise_settings_patch_req import ConnectWiseSettingsPatchReq
from jcapiv2.models.connect_wise_ticketing_alert_configuration import ConnectWiseTicketingAlertConfiguration
from jcapiv2.models.connect_wise_ticketing_alert_configuration_list import ConnectWiseTicketingAlertConfigurationList
from jcapiv2.models.connect_wise_ticketing_alert_configuration_option import ConnectWiseTicketingAlertConfigurationOption
from jcapiv2.models.connect_wise_ticketing_alert_configuration_options import ConnectWiseTicketingAlertConfigurationOptions
from jcapiv2.models.connect_wise_ticketing_alert_configuration_request import ConnectWiseTicketingAlertConfigurationRequest
from jcapiv2.models.connectwise_addition import ConnectwiseAddition
from jcapiv2.models.connectwise_agreement import ConnectwiseAgreement
from jcapiv2.models.connectwise_company import ConnectwiseCompany
from jcapiv2.models.connectwise_company_resp import ConnectwiseCompanyResp
from jcapiv2.models.connectwise_company_type_resp import ConnectwiseCompanyTypeResp
from jcapiv2.models.connectwise_integration import ConnectwiseIntegration
from jcapiv2.models.connectwise_integration_patch_req import ConnectwiseIntegrationPatchReq
from jcapiv2.models.connectwise_integration_req import ConnectwiseIntegrationReq
from jcapiv2.models.custom_email import CustomEmail
from jcapiv2.models.custom_email_template import CustomEmailTemplate
from jcapiv2.models.custom_email_template_field import CustomEmailTemplateField
from jcapiv2.models.custom_email_type import CustomEmailType
from jcapiv2.models.dep import DEP
from jcapiv2.models.dep_setup_assistant_option import DEPSetupAssistantOption
from jcapiv2.models.dep_welcome_screen import DEPWelcomeScreen
from jcapiv2.models.device_id_erase_body import DeviceIdEraseBody
from jcapiv2.models.device_id_lock_body import DeviceIdLockBody
from jcapiv2.models.device_id_restart_body import DeviceIdRestartBody
from jcapiv2.models.directory import Directory
from jcapiv2.models.duo_account import DuoAccount
from jcapiv2.models.duo_application import DuoApplication
from jcapiv2.models.duo_application_req import DuoApplicationReq
from jcapiv2.models.duo_application_update_req import DuoApplicationUpdateReq
from jcapiv2.models.error import Error
from jcapiv2.models.error_details import ErrorDetails
from jcapiv2.models.feature import Feature
from jcapiv2.models.filter import Filter
from jcapiv2.models.filter_query import FilterQuery
from jcapiv2.models.g_suite_builtin_translation import GSuiteBuiltinTranslation
from jcapiv2.models.g_suite_direction_translation import GSuiteDirectionTranslation
from jcapiv2.models.g_suite_translation_rule import GSuiteTranslationRule
from jcapiv2.models.g_suite_translation_rule_request import GSuiteTranslationRuleRequest
from jcapiv2.models.graph_attribute_ldap_groups import GraphAttributeLdapGroups
from jcapiv2.models.graph_attribute_posix_groups import GraphAttributePosixGroups
from jcapiv2.models.graph_attribute_posix_groups_posix_groups import GraphAttributePosixGroupsPosixGroups
from jcapiv2.models.graph_attribute_radius import GraphAttributeRadius
from jcapiv2.models.graph_attribute_radius_radius import GraphAttributeRadiusRadius
from jcapiv2.models.graph_attribute_radius_radius_reply import GraphAttributeRadiusRadiusReply
from jcapiv2.models.graph_attribute_samba_enabled import GraphAttributeSambaEnabled
from jcapiv2.models.graph_attribute_sudo import GraphAttributeSudo
from jcapiv2.models.graph_attribute_sudo_sudo import GraphAttributeSudoSudo
from jcapiv2.models.graph_attributes import GraphAttributes
from jcapiv2.models.graph_connection import GraphConnection
from jcapiv2.models.graph_object import GraphObject
from jcapiv2.models.graph_object_with_paths import GraphObjectWithPaths
from jcapiv2.models.graph_operation import GraphOperation
from jcapiv2.models.graph_operation_active_directory import GraphOperationActiveDirectory
from jcapiv2.models.graph_operation_application import GraphOperationApplication
from jcapiv2.models.graph_operation_command import GraphOperationCommand
from jcapiv2.models.graph_operation_g_suite import GraphOperationGSuite
from jcapiv2.models.graph_operation_ldap_server import GraphOperationLdapServer
from jcapiv2.models.graph_operation_office365 import GraphOperationOffice365
from jcapiv2.models.graph_operation_policy import GraphOperationPolicy
from jcapiv2.models.graph_operation_policy_group import GraphOperationPolicyGroup
from jcapiv2.models.graph_operation_policy_group_member import GraphOperationPolicyGroupMember
from jcapiv2.models.graph_operation_radius_server import GraphOperationRadiusServer
from jcapiv2.models.graph_operation_software_app import GraphOperationSoftwareApp
from jcapiv2.models.graph_operation_system import GraphOperationSystem
from jcapiv2.models.graph_operation_system_group import GraphOperationSystemGroup
from jcapiv2.models.graph_operation_system_group_member import GraphOperationSystemGroupMember
from jcapiv2.models.graph_operation_user import GraphOperationUser
from jcapiv2.models.graph_operation_user_group import GraphOperationUserGroup
from jcapiv2.models.graph_operation_user_group_member import GraphOperationUserGroupMember
from jcapiv2.models.graph_type import GraphType
from jcapiv2.models.group import Group
from jcapiv2.models.group_attributes_user_group import GroupAttributesUserGroup
from jcapiv2.models.group_id_suggestions_body import GroupIdSuggestionsBody
from jcapiv2.models.group_type import GroupType
from jcapiv2.models.gsuite_output import GsuiteOutput
from jcapiv2.models.gsuite_patch_input import GsuitePatchInput
from jcapiv2.models.ip_list import IPList
from jcapiv2.models.ip_list_request import IPListRequest
from jcapiv2.models.import_user import ImportUser
from jcapiv2.models.import_user_address import ImportUserAddress
from jcapiv2.models.import_user_phone_number import ImportUserPhoneNumber
from jcapiv2.models.import_users_response import ImportUsersResponse
from jcapiv2.models.inline_response200 import InlineResponse200
from jcapiv2.models.inline_response2001 import InlineResponse2001
from jcapiv2.models.inline_response20010 import InlineResponse20010
from jcapiv2.models.inline_response20011 import InlineResponse20011
from jcapiv2.models.inline_response20011_users import InlineResponse20011Users
from jcapiv2.models.inline_response20012 import InlineResponse20012
from jcapiv2.models.inline_response20013 import InlineResponse20013
from jcapiv2.models.inline_response2002 import InlineResponse2002
from jcapiv2.models.inline_response2002_users import InlineResponse2002Users
from jcapiv2.models.inline_response2003 import InlineResponse2003
from jcapiv2.models.inline_response2004 import InlineResponse2004
from jcapiv2.models.inline_response2005 import InlineResponse2005
from jcapiv2.models.inline_response2006 import InlineResponse2006
from jcapiv2.models.inline_response2007 import InlineResponse2007
from jcapiv2.models.inline_response2008 import InlineResponse2008
from jcapiv2.models.inline_response2009 import InlineResponse2009
from jcapiv2.models.inline_response201 import InlineResponse201
from jcapiv2.models.inline_response400 import InlineResponse400
from jcapiv2.models.integration import Integration
from jcapiv2.models.integration_sync_error import IntegrationSyncError
from jcapiv2.models.integration_sync_error_resp import IntegrationSyncErrorResp
from jcapiv2.models.integration_type import IntegrationType
from jcapiv2.models.integrations_response import IntegrationsResponse
from jcapiv2.models.job_id import JobId
from jcapiv2.models.job_workresult import JobWorkresult
from jcapiv2.models.ldap_group import LdapGroup
from jcapiv2.models.ldap_server_action import LdapServerAction
from jcapiv2.models.ldap_server_input import LdapServerInput
from jcapiv2.models.ldap_server_output import LdapServerOutput
from jcapiv2.models.ldapservers_id_body import LdapserversIdBody
from jcapiv2.models.member_suggestion import MemberSuggestion
from jcapiv2.models.member_suggestions_post_result import MemberSuggestionsPostResult
from jcapiv2.models.mobileconfig import Mobileconfig
from jcapiv2.models.os_restriction import OSRestriction
from jcapiv2.models.os_restriction_apple_restrictions import OSRestrictionAppleRestrictions
from jcapiv2.models.office365_builtin_translation import Office365BuiltinTranslation
from jcapiv2.models.office365_direction_translation import Office365DirectionTranslation
from jcapiv2.models.office365_output import Office365Output
from jcapiv2.models.office365_patch_input import Office365PatchInput
from jcapiv2.models.office365_translation_rule import Office365TranslationRule
from jcapiv2.models.office365_translation_rule_request import Office365TranslationRuleRequest
from jcapiv2.models.organization import Organization
from jcapiv2.models.organization_case import OrganizationCase
from jcapiv2.models.organization_cases_response import OrganizationCasesResponse
from jcapiv2.models.phone_number import PhoneNumber
from jcapiv2.models.policy import Policy
from jcapiv2.models.policy_group import PolicyGroup
from jcapiv2.models.policy_group_data import PolicyGroupData
from jcapiv2.models.policy_request import PolicyRequest
from jcapiv2.models.policy_request_template import PolicyRequestTemplate
from jcapiv2.models.policy_result import PolicyResult
from jcapiv2.models.policy_template import PolicyTemplate
from jcapiv2.models.policy_template_config_field import PolicyTemplateConfigField
from jcapiv2.models.policy_template_config_field_tooltip import PolicyTemplateConfigFieldTooltip
from jcapiv2.models.policy_template_config_field_tooltip_variables import PolicyTemplateConfigFieldTooltipVariables
from jcapiv2.models.policy_template_with_details import PolicyTemplateWithDetails
from jcapiv2.models.policy_value import PolicyValue
from jcapiv2.models.policy_with_details import PolicyWithDetails
from jcapiv2.models.provider import Provider
from jcapiv2.models.provider_admin_req import ProviderAdminReq
from jcapiv2.models.provider_invoice import ProviderInvoice
from jcapiv2.models.provider_invoice_response import ProviderInvoiceResponse
from jcapiv2.models.push_endpoint_response import PushEndpointResponse
from jcapiv2.models.push_endpoint_response_device import PushEndpointResponseDevice
from jcapiv2.models.pushendpoints_push_endpoint_id_body import PushendpointsPushEndpointIdBody
from jcapiv2.models.pwm_all_users import PwmAllUsers
from jcapiv2.models.pwm_all_users_groups import PwmAllUsersGroups
from jcapiv2.models.pwm_all_users_results import PwmAllUsersResults
from jcapiv2.models.pwm_overview_app_versions import PwmOverviewAppVersions
from jcapiv2.models.pwm_overview_app_versions_results import PwmOverviewAppVersionsResults
from jcapiv2.models.pwm_overview_main import PwmOverviewMain
from jcapiv2.models.pwm_overview_main_devices import PwmOverviewMainDevices
from jcapiv2.models.query import Query
from jcapiv2.models.queued_command_list import QueuedCommandList
from jcapiv2.models.queued_command_list_results import QueuedCommandListResults
from jcapiv2.models.samba_domain_input import SambaDomainInput
from jcapiv2.models.samba_domain_output import SambaDomainOutput
from jcapiv2.models.scheduled_userstate_result import ScheduledUserstateResult
from jcapiv2.models.setup_assistant_option import SetupAssistantOption
from jcapiv2.models.shared_folder_access_levels import SharedFolderAccessLevels
from jcapiv2.models.shared_folder_access_levels_results import SharedFolderAccessLevelsResults
from jcapiv2.models.shared_folder_details import SharedFolderDetails
from jcapiv2.models.shared_folder_users import SharedFolderUsers
from jcapiv2.models.shared_folder_users_results import SharedFolderUsersResults
from jcapiv2.models.shared_folders_list import SharedFoldersList
from jcapiv2.models.shared_folders_list_results import SharedFoldersListResults
from jcapiv2.models.software_app import SoftwareApp
from jcapiv2.models.software_app_apple_vpp import SoftwareAppAppleVpp
from jcapiv2.models.software_app_reclaim_licenses import SoftwareAppReclaimLicenses
from jcapiv2.models.software_app_settings import SoftwareAppSettings
from jcapiv2.models.software_app_status import SoftwareAppStatus
from jcapiv2.models.software_app_with_status import SoftwareAppWithStatus
from jcapiv2.models.software_apps_retry_installation_request import SoftwareAppsRetryInstallationRequest
from jcapiv2.models.subscription import Subscription
from jcapiv2.models.suggestion_counts import SuggestionCounts
from jcapiv2.models.system_group import SystemGroup
from jcapiv2.models.system_group_data import SystemGroupData
from jcapiv2.models.system_insights_alf import SystemInsightsAlf
from jcapiv2.models.system_insights_alf_exceptions import SystemInsightsAlfExceptions
from jcapiv2.models.system_insights_alf_explicit_auths import SystemInsightsAlfExplicitAuths
from jcapiv2.models.system_insights_appcompat_shims import SystemInsightsAppcompatShims
from jcapiv2.models.system_insights_apps import SystemInsightsApps
from jcapiv2.models.system_insights_authorized_keys import SystemInsightsAuthorizedKeys
from jcapiv2.models.system_insights_azure_instance_metadata import SystemInsightsAzureInstanceMetadata
from jcapiv2.models.system_insights_azure_instance_tags import SystemInsightsAzureInstanceTags
from jcapiv2.models.system_insights_battery import SystemInsightsBattery
from jcapiv2.models.system_insights_bitlocker_info import SystemInsightsBitlockerInfo
from jcapiv2.models.system_insights_browser_plugins import SystemInsightsBrowserPlugins
from jcapiv2.models.system_insights_certificates import SystemInsightsCertificates
from jcapiv2.models.system_insights_chassis_info import SystemInsightsChassisInfo
from jcapiv2.models.system_insights_chrome_extensions import SystemInsightsChromeExtensions
from jcapiv2.models.system_insights_connectivity import SystemInsightsConnectivity
from jcapiv2.models.system_insights_crashes import SystemInsightsCrashes
from jcapiv2.models.system_insights_cups_destinations import SystemInsightsCupsDestinations
from jcapiv2.models.system_insights_disk_encryption import SystemInsightsDiskEncryption
from jcapiv2.models.system_insights_disk_info import SystemInsightsDiskInfo
from jcapiv2.models.system_insights_dns_resolvers import SystemInsightsDnsResolvers
from jcapiv2.models.system_insights_etc_hosts import SystemInsightsEtcHosts
from jcapiv2.models.system_insights_firefox_addons import SystemInsightsFirefoxAddons
from jcapiv2.models.system_insights_groups import SystemInsightsGroups
from jcapiv2.models.system_insights_ie_extensions import SystemInsightsIeExtensions
from jcapiv2.models.system_insights_interface_addresses import SystemInsightsInterfaceAddresses
from jcapiv2.models.system_insights_interface_details import SystemInsightsInterfaceDetails
from jcapiv2.models.system_insights_kernel_info import SystemInsightsKernelInfo
from jcapiv2.models.system_insights_launchd import SystemInsightsLaunchd
from jcapiv2.models.system_insights_linux_packages import SystemInsightsLinuxPackages
from jcapiv2.models.system_insights_logged_in_users import SystemInsightsLoggedInUsers
from jcapiv2.models.system_insights_logical_drives import SystemInsightsLogicalDrives
from jcapiv2.models.system_insights_managed_policies import SystemInsightsManagedPolicies
from jcapiv2.models.system_insights_mounts import SystemInsightsMounts
from jcapiv2.models.system_insights_os_version import SystemInsightsOsVersion
from jcapiv2.models.system_insights_patches import SystemInsightsPatches
from jcapiv2.models.system_insights_programs import SystemInsightsPrograms
from jcapiv2.models.system_insights_python_packages import SystemInsightsPythonPackages
from jcapiv2.models.system_insights_safari_extensions import SystemInsightsSafariExtensions
from jcapiv2.models.system_insights_scheduled_tasks import SystemInsightsScheduledTasks
from jcapiv2.models.system_insights_secureboot import SystemInsightsSecureboot
from jcapiv2.models.system_insights_services import SystemInsightsServices
from jcapiv2.models.system_insights_shadow import SystemInsightsShadow
from jcapiv2.models.system_insights_shared_folders import SystemInsightsSharedFolders
from jcapiv2.models.system_insights_shared_resources import SystemInsightsSharedResources
from jcapiv2.models.system_insights_sharing_preferences import SystemInsightsSharingPreferences
from jcapiv2.models.system_insights_sip_config import SystemInsightsSipConfig
from jcapiv2.models.system_insights_startup_items import SystemInsightsStartupItems
from jcapiv2.models.system_insights_system_controls import SystemInsightsSystemControls
from jcapiv2.models.system_insights_system_info import SystemInsightsSystemInfo
from jcapiv2.models.system_insights_tpm_info import SystemInsightsTpmInfo
from jcapiv2.models.system_insights_uptime import SystemInsightsUptime
from jcapiv2.models.system_insights_usb_devices import SystemInsightsUsbDevices
from jcapiv2.models.system_insights_user_groups import SystemInsightsUserGroups
from jcapiv2.models.system_insights_user_ssh_keys import SystemInsightsUserSshKeys
from jcapiv2.models.system_insights_userassist import SystemInsightsUserassist
from jcapiv2.models.system_insights_users import SystemInsightsUsers
from jcapiv2.models.system_insights_wifi_networks import SystemInsightsWifiNetworks
from jcapiv2.models.system_insights_wifi_status import SystemInsightsWifiStatus
from jcapiv2.models.system_insights_windows_security_center import SystemInsightsWindowsSecurityCenter
from jcapiv2.models.system_insights_windows_security_products import SystemInsightsWindowsSecurityProducts
from jcapiv2.models.systemfdekey import Systemfdekey
from jcapiv2.models.ticketing_integration_alert import TicketingIntegrationAlert
from jcapiv2.models.ticketing_integration_alerts_resp import TicketingIntegrationAlertsResp
from jcapiv2.models.user import User
from jcapiv2.models.user_group import UserGroup
from jcapiv2.models.user_group_post import UserGroupPost
from jcapiv2.models.user_group_put import UserGroupPut
from jcapiv2.models.workday_fields import WorkdayFields
from jcapiv2.models.workday_input import WorkdayInput
from jcapiv2.models.workday_output import WorkdayOutput
from jcapiv2.models.workday_worker import WorkdayWorker
from jcapiv2.models.workdayoutput_auth import WorkdayoutputAuth
